name: 💡 ไอเดียการทำเบียร์ (Brewing Idea)
description: บันทึกความคิดหรือความอยากรู้เกี่ยวกับการทำเบียร์
labels: ["idea", "curiosity", "brewing", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 ไอเดียการทำเบียร์
        จุดเริ่มต้นสำหรับความคิดหรือความอยากรู้ใดๆ เกี่ยวกับการทำเบียร์ที่อยากสำรวจ

  - type: input
    id: idea-topic
    attributes:
      label: หัวข้อไอเดีย
      description: ความคิดหรือความอยากรู้ของคุณเกี่ยวกับอะไร?
      placeholder: "เช่น ทำไมเบียร์บางแบบถึงมีรสขม, เบียร์ที่ใช้วัตถุดิบไทย, ผลของน้ำต่อรสชาติ"
    validations:
      required: true

  - type: textarea
    id: initial-thoughts
    attributes:
      label: ความคิดเริ่มต้น
      description: อธิบายไอเดียหรือความสงสัยของคุณ
      placeholder: |
        - สิ่งที่สงสัยหรืออยากรู้
        - ที่มาของความคิดนี้
        - สิ่งที่คาดว่าจะเรียนรู้
        - แรงบันดาลใจหรือประสบการณ์ที่เกี่ยวข้อง
    validations:
      required: true

  - type: checkboxes
    id: interest-areas
    attributes:
      label: พื้นที่ที่สนใจ
      description: เลือกด้านที่เกี่ยวข้องกับไอเดียของคุณ
      options:
        - label: วัตถุดิบ (มอลต์ ฮอปส์ ยีสต์ น้ำ)
        - label: กระบวนการทำเบียร์
        - label: สไตล์เบียร์และรสชาติ
        - label: วิทยาศาสตร์การหมัก
        - label: วัตถุดิบท้องถิ่น/ไทย
        - label: อุปกรณ์และเทคโนโลยี
        - label: ประวัติศาสตร์และวัฒนธรรม
        - label: การแก้ไขปัญหา

  - type: dropdown
    id: urgency
    attributes:
      label: ความเร่งด่วน
      description: คุณอยากสำรวจไอเดียนี้แค่ไหน?
      options:
        - แค่อยากรู้ - ไม่เร่งด่วน
        - สนใจมาก - อยากเริ่มเร็วๆ นี้
        - เร่งด่วน - ต้องการคำตอบเพื่อโครงการปัจจุบัน
        - วิกฤต - จำเป็นต้องรู้ทันที
    validations:
      required: true

  - type: textarea
    id: what-you-know
    attributes:
      label: สิ่งที่รู้อยู่แล้ว
      description: คุณรู้อะไรเกี่ยวกับหัวข้อนี้อยู่บ้างแล้ว?
      placeholder: "ความรู้พื้นฐานที่มี, ประสบการณ์ที่เกี่ยวข้อง, หรือสิ่งที่เคยได้ยินมา"

  - type: textarea
    id: hoped-outcomes
    attributes:
      label: สิ่งที่หวังจะได้
      description: คุณหวังว่าจะได้อะไรจากการสำรวจไอเดียนี้?
      placeholder: |
        - ความเข้าใจที่ลึกขึ้น
        - สูตรเบียร์ใหม่
        - วิธีแก้ปัญหา
        - ทักษะใหม่
        - ความรู้เพื่อแบ่งปัน

  - type: checkboxes
    id: next-steps
    attributes:
      label: ขั้นตอนถัดไป
      description: สิ่งที่คุณคิดว่าควรทำต่อ
      options:
        - label: ทำการวิจัยเชิงลึก (Deep Research Request)
        - label: หาข้อมูลเบื้องต้นก่อน
        - label: พูดคุยกับผู้เชี่ยวชาญ
        - label: ทดลองขนาดเล็ก
        - label: ยังไม่แน่ใจ - ต้องการคำแนะนำ

  - type: textarea
    id: additional-context
    attributes:
      label: บริบทเพิ่มเติม
      description: มีอะไรอื่นที่ควรรู้เกี่ยวกับไอเดียนี้?
      placeholder: "เหตุการณ์ที่นำมาสู่ไอเดีย, เป้าหมายระยะยาว, ข้อจำกัด, หรือความท้าทายที่คาดว่าจะพบ"