name: 💡 ไอเดียการทำเบียร์ (Brewing Idea)
description: บันทึกความคิดหรือความอยากรู้เกี่ยวกับการทำเบียร์
labels: ["idea", "curiosity", "brewing", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 ไอเดียการทำเบียร์
        จุดเริ่มต้นสำหรับความคิดหรือความอยากรู้ใดๆ เกี่ยวกับการทำเบียร์

  - type: textarea
    id: brewing-idea
    attributes:
      label: ไอเดียการทำเบียร์
      description: ความคิดหรือความอยากรู้ของคุณเกี่ยวกับการทำเบียร์
      placeholder: "เช่น ทำไมเบียร์บางแบบถึงมีรสขม, เบียร์ที่ใช้วัตถุดิบไทย, ผลของน้ำต่อรสชาติ"
    validations:
      required: true