name: 💡 ไอเดียการทำเบียร์ (Brewing Idea)
description: บันทึกความคิดหรือความอยากรู้เกี่ยวกับการทำเบียร์
labels: ["idea", "curiosity", "brewing", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## 💡 ไอเดียการทำเบียร์
        จุดเริ่มต้นสำหรับความคิดหรือความอยากรู้ใดๆ เกี่ยวกับการทำเบียร์

  - type: input
    id: idea-topic
    attributes:
      label: หัวข้อไอเดีย
      description: ความคิดหรือความอยากรู้ของคุณเกี่ยวกับอะไร?
      placeholder: "เช่น ทำไมเบียร์บางแบบถึงมีรสขม, เบียร์ที่ใช้วัตถุดิบไทย, ผลของน้ำต่อรสชาติ"
    validations:
      required: true

  - type: textarea
    id: idea-description
    attributes:
      label: ความคิดเริ่มต้น
      description: อธิบายไอเดียหรือความสงสัยของคุณ
      placeholder: |
        - สิ่งที่สงสัยหรืออยากรู้
        - ที่มาของความคิดนี้
        - สิ่งที่คาดว่าจะเรียนรู้
    validations:
      required: true