name: 🍻 การวางแผนวันทำเบียร์ (Brew Day Planning)
description: วางแผนและติดตามการทำเบียร์
labels: ["brew-day", "planning", "brewing", "thai"]
body:
  - type: input
    id: recipe-name
    attributes:
      label: ชื่อสูตร
      description: คุณจะทำเบียร์สูตรไหน?
      placeholder: "เช่น Belgian Golden Strong Ale, Thai Wheat Beer"
    validations:
      required: true
  
  - type: input
    id: recipe-file
    attributes:
      label: ไฟล์สูตร
      description: ที่อยู่ของไฟล์สูตร
      placeholder: "เช่น recipes/r001-belgian-golden-strong-ale.md"
  
  - type: input
    id: planned-date
    attributes:
      label: วันที่วางแผนทำเบียร์
      description: คุณวางแผนจะทำเบียร์เมื่อไหร่?
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
  
  - type: input
    id: batch-number
    attributes:
      label: หมายเลขชุดการทำ
      description: รหัสการติดตาม
      placeholder: "เช่น BGS-001, IPA-003, TWB-001"
  
  - type: checkboxes
    id: pre-brew-prep
    attributes:
      label: การเตรียมการก่อนทำเบียร์
      description: งานที่ต้องทำให้เสร็จก่อนวันทำเบียร์
      options:
        - label: จัดหาวัตถุดิบทั้งหมด
        - label: ตรวจสอบสภาพอุปกรณ์
        - label: วางแผนการปรับแต่งน้ำ
        - label: เตรียมยีสต์สตาร์เตอร์ (หากจำเป็น)
        - label: ทำความสะอาดและฆ่าเชื้ออุปกรณ์
        - label: ทบทวนสูตรและกระบวนการ
        - label: ตรวจสอบสภาพอากาศ
  
  - type: checkboxes
    id: brew-day-tasks
    attributes:
      label: งานในวันทำเบียร์
      description: ขั้นตอนสำคัญในกระบวนการทำเบียร์
      options:
        - label: การปรับแต่งน้ำ
        - label: การบด (Mashing)
        - label: การแยกน้ำหวาน (Lautering/Sparging)
        - label: การต้ม (Boiling)
        - label: การใส่ฮอปส์
        - label: การทำให้เย็น (Cooling)
        - label: การย้ายไปถังหมัก
        - label: การใส่ยีสต์
        - label: การบันทึกการวัด
  
  - type: textarea
    id: measurements-plan
    attributes:
      label: การวัดที่จะติดตาม
      description: คุณจะบันทึกการวัดอะไรบ้าง?
      value: |
        - [ ] pH ของการบด
        - [ ] ความหนาแน่นก่อนต้ม
        - [ ] ปริมาตรก่อนต้ม
        - [ ] ปริมาตรหลังต้ม
        - [ ] ความหนาแน่นเริ่มต้น (OG)
        - [ ] ปริมาตรในถังหมัก
        - [ ] อุณหภูมิการใส่ยีสต์
  
  - type: textarea
    id: recipe-modifications
    attributes:
      label: การแก้ไขสูตร
      description: การเปลี่ยนแปลงที่วางแผนไว้จากสูตรพื้นฐาน
      placeholder: "เช่น เปลี่ยนฮอปส์, ปรับปริมาณ, เปลี่ยนกระบวนการ"
  
  - type: textarea
    id: notes
    attributes:
      label: หมายเหตุเพิ่มเติม
      description: หมายเหตุการวางแผนหรือข้อพิจารณาอื่นๆ
  
  - type: dropdown
    id: collaborators
    attributes:
      label: คู่หูทำเบียร์
      description: ใครมีส่วนร่วมในการทำเบียร์ครั้งนี้?
      options:
        - ทำคนเดียว
        - ทำร่วมกัน
        - โรงเบียร์คู่หู
        - ความร่วมมือแบบมืออาชีพ
        - คู่หูอื่นๆ
  
  - type: checkboxes
    id: post-brew
    attributes:
      label: งานหลังทำเบียร์
      description: งานติดตามหลังจากทำเบียร์
      options:
        - label: อัพเดตไฟล์สูตรด้วยการวัดจริง
        - label: สร้างบันทึกการติดตามการหมัก
        - label: กำหนดตารางการอ่านความหนาแน่น
        - label: วางแผนระยะเวลาการบรรจุ
        - label: บันทึกปัญหาหรือการเรียนรู้