name: 🧪 การทดลองการทำเบียร์ (Brewing Experiment)
description: ออกแบบและดำเนินการทดลองการทำเบียร์แบบควบคุม
labels: ["experiment", "brewing", "science", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## การทดลองการทำเบียร์
        ออกแบบการทดลองทางวิทยาศาสตร์เพื่อทดสอบสมมติฐานจากการวิจัยหรือเปรียบเทียบวิธีการต่างๆ

  - type: input
    id: experiment-name
    attributes:
      label: ชื่อการทดลอง
      description: ชื่อของการทดลองที่จะดำเนินการ
      placeholder: "เช่น เปรียบเทียบมอลต์ BB vs Weyermann, ทดสอบ Dry Hop Timing"
    validations:
      required: true

  - type: input
    id: research-basis
    attributes:
      label: พื้นฐานการวิจัย
      description: การวิจัยหรือสูตรที่เป็นพื้นฐานของการทดลอง
      placeholder: "#123 หรือ ชื่อเอกสารวิจัย/สูตร"
    validations:
      required: true

  - type: textarea
    id: hypothesis
    attributes:
      label: สมมติฐาน
      description: สิ่งที่คาดว่าจะเกิดขึ้นจากการทดลองนี้
      placeholder: |
        เราคาดว่า... เพราะว่า...
        ตัวอย่าง: "เราคาดว่า BB Extra Pale จะให้สีที่อ่อนกว่าและประสิทธิภาพที่สูงกว่า Weyermann Pale Ale เพราะว่าข้อมูลทางเทคนิคแสดงว่ามี EBC ต่ำกว่าและเอนไซม์สูงกว่า"
    validations:
      required: true

  - type: dropdown
    id: experiment-type
    attributes:
      label: ประเภทการทดลอง
      description: ประเภทของการทดลองที่จะทำ
      options:
        - การเปรียบเทียบวัตถุดิบ (Ingredient Comparison)
        - การทดสอบกระบวนการ (Process Testing)
        - การปรับปรุงสูตร (Recipe Optimization)
        - การควบคุมคุณภาพ (Quality Control)
        - การทดลองใหม่ (Novel Experiment)
        - การยืนยันการวิจัย (Research Validation)
    validations:
      required: true

  - type: textarea
    id: variables
    attributes:
      label: ตัวแปรการทดลอง
      description: ระบุตัวแปรอิสระ ตัวแปรตาม และตัวแปรควบคุม
      value: |
        **ตัวแปรอิสระ (Independent Variables):**
        - 

        **ตัวแปรตาม (Dependent Variables):**
        - 

        **ตัวแปรควบคุม (Controlled Variables):**
        - 
    validations:
      required: true

  - type: checkboxes
    id: measurements
    attributes:
      label: การวัดและบันทึกข้อมูล
      description: ข้อมูลอะไรที่จะวัดและบันทึก?
      options:
        - label: ค่า pH ในขั้นตอนต่างๆ
        - label: ประสิทธิภาพการสกัด (Extract Efficiency)
        - label: ค่าความหนาแน่น (OG, FG)
        - label: สีของเบียร์ (SRM/EBC)
        - label: ความขมของเบียร์ (IBU)
        - label: การประเมินทางประสาทสัมผัส
        - label: การวิเคราะห์ทางเคมี
        - label: เวลาและอุณหภูมิในแต่ละขั้นตอน
        - label: การถ่ายภาพและบันทึกภาพ

  - type: textarea
    id: methodology
    attributes:
      label: วิธีการดำเนินการ
      description: ขั้นตอนการดำเนินการทดลองอย่างละเอียด
      placeholder: |
        1. การเตรียมวัตถุดิบและอุปกรณ์
        2. ขั้นตอนการทำเบียร์แบบเดียวกัน
        3. จุดที่แตกต่างกันในการทดลอง
        4. การบันทึกข้อมูลและการวัด
        5. การเก็บตัวอย่างและการวิเคราะห์
    validations:
      required: true

  - type: textarea
    id: success-criteria
    attributes:
      label: เกณฑ์ความสำเร็จ
      description: จะรู้ได้อย่างไรว่าการทดลองสำเร็จ?
      placeholder: |
        - สามารถวัดความแตกต่างที่มีนัยสำคัญได้
        - ได้ข้อมูลครบถ้วนตามแผน
        - สามารถสรุปผลและให้ข้อแนะนำได้
        - เกิดการเรียนรู้ที่มีประโยชน์

  - type: input
    id: sample-size
    attributes:
      label: ขนาดตัวอย่าง
      description: จำนวนชุดการทดลองและขนาดแต่ละชุด
      placeholder: "เช่น 2 ชุด ขนาด 5 ลิตรต่อชุด"

  - type: textarea
    id: timeline
    attributes:
      label: กำหนดเวลา
      description: ระยะเวลาการดำเนินการทดลองและการวิเคราะห์
      value: |
        - การเตรียมการ: __ วัน
        - วันทำเบียร์: __
        - การหมัก: __ วัน
        - การวิเคราะห์: __ วัน
        - การสรุปผล: __ วัน

  - type: textarea
    id: expected-deliverables
    attributes:
      label: ผลลัพธ์ที่คาดหวัง
      description: สิ่งที่จะได้จากการทดลองนี้
      value: |
        - [ ] แผนการทดลองใน 003-experiments/planned/
        - [ ] ข้อมูลการทดลองใน 004-results/data/
        - [ ] การวิเคราะห์ผลใน 004-results/analysis/
        - [ ] บทสรุปและข้อแนะนำ
        - [ ] การปรับปรุงสูตรหรือกระบวนการ