name: 📊 ผลการทดลองและการวิเคราะห์ (Experiment Results & Analysis)
description: บันทึกและวิเคราะห์ผลการทดลองการทำเบียร์
labels: ["results", "analysis", "experiment", "data", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## การบันทึกผลการทดลอง
        การบันทึกผลการทดลองและการวิเคราะห์อย่างครอบคลุม

  - type: input
    id: experiment-reference
    attributes:
      label: การทดลองต้นฉบับ
      description: ลิงก์ไปยังการออกแบบการทดลอง
      placeholder: "Issue #XXX - ชื่อการทดลอง"
    validations:
      required: true
  
  - type: input
    id: completion-date
    attributes:
      label: วันที่เสร็จสิ้นการทดลอง
      description: การทดลองเสร็จสิ้นเมื่อไหร่?
      placeholder: "YYYY-MM-DD"
    validations:
      required: true
  
  - type: dropdown
    id: experiment-status
    attributes:
      label: สถานะการทดลอง
      description: สถานะโดยรวมของการทดลอง
      options:
        - สำเร็จ - สมมติฐานได้รับการยืนยัน
        - สำเร็จ - สมมติฐานถูกปฏิเสธ
        - สำเร็จบางส่วน - ผลลัพธ์แบบผสม
        - ล้มเหลว - ปัญหาทางเทคนิค
        - ดำเนินการอยู่ - มีผลลัพธ์บางส่วน
    validations:
      required: true
  
  - type: textarea
    id: raw-data-summary
    attributes:
      label: สรุปข้อมูลดิบ
      description: สรุปข้อมูลที่เก็บรวบรวม (ข้อมูลเต็มในไฟล์ CSV)
      value: |
        ## ข้อมูลเชิงปริมาณ
        | การวัด | กลุ่มควบคุม | ทดสอบ 1 | ทดสอบ 2 | หมายเหตุ |
        |---------|-------------|----------|----------|----------|
        | | | | | |
        
        ## การสังเกตเชิงคุณภาพ
        - ชุดควบคุม: [การสังเกต]
        - ชุดทดสอบ 1: [การสังเกต]
        - ชุดทดสอบ 2: [การสังเกต]
        
        **ข้อมูลเต็มที่:** brews/004-results/data/[การทดลอง]-data.csv
    validations:
      required: true
  
  - type: textarea
    id: statistical-analysis
    attributes:
      label: การวิเคราะห์ทางสิถิติ
      description: ผลการทดสอบทางสิถิติ
      placeholder: |
        ## การทดสอบที่ทำ: [เช่น Two-sample t-test]
        
        **สมมติฐานหลัก:** [ระบุ H0]
        **สมมติฐานรอง:** [ระบุ H1]
        
        **ผลลัพธ์:**
        - สถิติทดสอบ: [ค่า]
        - P-value: [ค่า]
        - ช่วงความเชื่อมั่น: [ช่วง]
        - ขนาดผล: [ค่า]
        
        **สรุป:** [ยอมรับ/ปฏิเสธ สมมติฐานหลัก]
  
  - type: textarea
    id: sensory-results
    attributes:
      label: ผลการประเมินทางประสาทสัมผัส
      description: ผลจากคณะผู้ชิมหรือการวิเคราะห์ทางประสาทสัมผัส
      placeholder: |
        ## รายละเอียดคณะผู้ชิม
        - จำนวนผู้ชิม: [X] คน
        - ประเภทการทดสอบ: [Triangle test, ความชอบ, ฯลฯ]
        
        ## ผลลัพธ์
        - การระบุที่ถูกต้อง: X/Y
        - ความชอบ: X% สำหรับ [ตัวอย่าง]
        - หมายเหตุการอธิบาย: [สรุปความคิดเห็น]
        
        ## นัยสำคัญทางสิถิติ
        - [มีนัยสำคัญ/ไม่มีนัยสำคัญ] ที่ p < 0.05
  
  - type: textarea
    id: key-findings
    attributes:
      label: ผลการค้นพบสำคัญ
      description: การค้นพบหลักจากการทดลอง
      value: |
        1. **การค้นพบ 1:** [ข้อความชัดเจนของสิ่งที่เรียนรู้]
           - ข้อมูลสนับสนุน: [ตัวเลข/การสังเกตเฉพาะ]
           - ความหมาย: [สิ่งนี้หมายถึงอะไรสำหรับการทำเบียร์]
        
        2. **การค้นพบ 2:** [ข้อความชัดเจน]
           - ข้อมูลสนับสนุน: [ตัวเลข/การสังเกตเฉพาะ]
           - ความหมาย: [สิ่งนี้หมายถึงอะไร]
        
        3. **การค้นพบ 3:** [ข้อความชัดเจน]
           - ข้อมูลสนับสนุน: [ตัวเลข/การสังเกตเฉพาะ]
           - ความหมาย: [สิ่งนี้หมายถึงอะไร]
    validations:
      required: true
  
  - type: textarea
    id: research-validation
    attributes:
      label: การยืนยันการวิจัย
      description: ผลลัพธ์เปรียบเทียบกับการวิจัยต้นฉบับอย่างไร?
      placeholder: |
        ## การทำนายจากการวิจัย vs. ผลลัพธ์จริง
        
        1. การวิจัยทำนาย: [X] → ผลลัพธ์: [Y] ✓/✗
        2. การวิจัยทำนาย: [X] → ผลลัพธ์: [Y] ✓/✗
        3. การวิจัยทำนาย: [X] → ผลลัพธ์: [Y] ✓/✗
        
        ## อธิบายความแตกต่าง
        [หากการทำนายไม่ตรงกัน อธิบายเหตุผล]
  
  - type: textarea
    id: recipe-impact
    attributes:
      label: ผลกระทบต่อการพัฒนาสูตร
      description: ผลลัพธ์เหล่านี้ส่งผลต่อการพัฒนาสูตรอย่างไร?
      placeholder: |
        ## การแก้ไขสูตรที่แนะนำ
        - การเปลี่ยนแปลง 1: [อิงจากการค้นพบ X]
        - การเปลี่ยนแปลง 2: [อิงจากการค้นพบ Y]
        
        ## พารามิเตอร์สูตรใหม่
        - [พารามิเตอร์]: [ค่าใหม่] (เดิมคือ [ค่าเก่า])
        - [พารามิเตอร์]: [ค่าใหม่] (เดิมคือ [ค่าเก่า])
  
  - type: textarea
    id: future-experiments
    attributes:
      label: การทดลองติดตามที่จำเป็น
      description: การทดลองเพิ่มเติมอะไรที่แนะนำ?
      placeholder: |
        1. **การทดลอง:** [ชื่อเรื่อง]
           - เหตุผล: [ทำไมจึงจำเป็นอิงจากผลลัพธ์นี้]
           - ตัวแปร: [สิ่งที่จะทดสอบ]
        
        2. **การทดลอง:** [ชื่อเรื่อง]
           - เหตุผล: [ทำไมจึงจำเป็น]
           - ตัวแปร: [สิ่งที่จะทดสอบ]
  
  - type: textarea
    id: lessons-learned
    attributes:
      label: บทเรียนที่ได้เรียนรู้
      description: การปรับปรุงกระบวนการสำหรับการทดลองในอนาคต
      placeholder: |
        ## สิ่งที่ทำได้ดี
        - [กระบวนการ/วิธีการที่มีประสิทธิภาพ]
        
        ## สิ่งที่สามารถปรับปรุงได้
        - [ปัญหาที่พบ] → [วิธีแก้ไขครั้งหน้า]
        
        ## ข้อมูลเชิงลึกการออกแบบการทดลอง
        - [การเรียนรู้เกี่ยวกับวิธีการทดลอง]
  
  - type: checkboxes
    id: documentation-checklist
    attributes:
      label: ความสมบูรณ์ของเอกสาร
      description: ตรวจสอบให้แน่ใจว่าผลลัพธ์ทั้งหมดได้รับการบันทึกอย่างเหมาะสม
      options:
        - label: อัพโหลดข้อมูลดิบไปยัง 004-results/data/
        - label: สร้างเอกสารการวิเคราะห์ใน 004-results/analysis/
        - label: สรุปข้อสรุปใน 004-results/conclusions/
        - label: อัพเดตสูตรตามผลการค้นพบ
        - label: อัพเดตฐานความรู้ด้วยการเรียนรู้
        - label: สร้างการทดลองติดตามเป็น issues
        - label: อัพเดตเอกสารวิจัยด้วยการยืนยัน