name: 🍺 การพัฒนาสูตรเบียร์ (Recipe Development)
description: พัฒนาสูตรเบียร์ใหม่จากผลการวิจัย
labels: ["recipe", "development", "experimental", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## การพัฒนาสูตรเบียร์
        สร้างสูตรเบียร์ใหม่โดยอิงจากผลการวิจัยและหลักการทางวิทยาศาสตร์

  - type: input
    id: recipe-name
    attributes:
      label: ชื่อสูตร
      description: ชื่อของสูตรเบียร์ที่จะพัฒนา
      placeholder: "เช่น SMaSH Pale Ale with BB Malt, Thai Wheat Beer"
    validations:
      required: true

  - type: input
    id: research-source
    attributes:
      label: แหล่งที่มาของการวิจัย
      description: Issue หรือเอกสารวิจัยที่เป็นพื้นฐานของสูตรนี้
      placeholder: "#123 หรือ ชื่อเอกสารวิจัย"
    validations:
      required: true

  - type: dropdown
    id: beer-style
    attributes:
      label: สไตล์เบียร์
      description: สไตล์เบียร์ที่ต้องการพัฒนา
      options:
        - American Pale Ale
        - IPA (India Pale Ale)
        - NEIPA (New England IPA)
        - Wheat Beer / Hefeweizen
        - Lager
        - Pilsner
        - Stout / Porter
        - Belgian Ale
        - Saison
        - Sour Beer
        - Experimental / Hybrid
        - Thai-inspired Beer
    validations:
      required: true

  - type: textarea
    id: recipe-concept
    attributes:
      label: แนวคิดสูตร
      description: อธิบายแนวคิดและเป้าหมายของสูตรนี้
      placeholder: |
        - วัตถุประสงค์ของสูตร
        - ลักษณะเด่นที่ต้องการ
        - การประยุกต์ใช้การวิจัย
        - ความแตกต่างจากสูตรมาตรฐาน
    validations:
      required: true

  - type: textarea
    id: target-specs
    attributes:
      label: ข้อมูลจำเพาะเป้าหมาย
      description: ข้อมูลจำเพาะที่ต้องการของเบียร์
      value: |
        - ABV: __%
        - IBU: __
        - SRM/EBC: __
        - ขนาด: __ ลิตร
        - OG: __
        - FG: __
    validations:
      required: true

  - type: checkboxes
    id: key-ingredients
    attributes:
      label: วัตถุดิบหลัก
      description: วัตถุดิบสำคัญที่จะใช้ในสูตร
      options:
        - label: มอลต์พิเศษ (ระบุประเภท)
        - label: ฮอปส์พิเศษ (ระบุพันธุ์)
        - label: ยีสต์พิเศษ (ระบุสายพันธุ์)
        - label: น้ำที่ปรับแต่ง (ระบุโปรไฟล์)
        - label: วัตถุดิบเสริมรส (ระบุประเภท)
        - label: วัตถุดิบท้องถิน (ระบุแหล่งที่มา)

  - type: textarea
    id: brewing-notes
    attributes:
      label: หมายเหตุการทำเบียร์
      description: ข้อสังเกตพิเศษสำหรับกระบวนการทำเบียร์
      placeholder: |
        - เทคนิคการบด (mashing) พิเศษ
        - การต้มที่ต้องระวัง
        - การหมักที่ต้องควบคุม
        - อุณหภูมิและเวลาที่สำคัญ

  - type: dropdown
    id: difficulty-level
    attributes:
      label: ระดับความยาก
      description: ระดับความยากของสูตรนี้
      options:
        - ง่าย - เหมาะสำหรับผู้เริ่มต้น
        - ปานกลาง - ต้องการประสบการณ์บ้าง
        - ยาก - ต้องการทักษะและอุปกรณ์ขั้นสูง
        - ขั้นสูง - เฉพาะผู้เชี่ยวชาญ
    validations:
      required: true

  - type: textarea
    id: expected-outcomes
    attributes:
      label: ผลลัพธ์ที่คาดหวัง
      description: สิ่งที่คาดว่าจะได้จากการพัฒนาสูตรนี้
      value: |
        - [ ] สูตรสมบูรณ์ใน 002-recipes/experimental/
        - [ ] แผนการทดลองใน 003-experiments/planned/
        - [ ] การคำนวณและปรับปรุงในอนาคต
        - [ ] การประเมินต้นทุนและความเป็นไปได้

  - type: textarea
    id: testing-plan
    attributes:
      label: แผนการทดสอบ
      description: วิธีการทดสอบและประเมินสูตร
      placeholder: |
        - การทดสอบขนาดเล็กก่อน
        - การวัดและบันทึกข้อมูล
        - การทดสอบรสชาติ
        - การปรับปรุงตามผลลัพธ์