name: 📋 เทมเพลตคำแนะนำการวิจัย (Research Prompt Template)
description: คำแนะนำที่มีโครงสร้างสำหรับการดำเนินการวิจัยการทำเบียร์
labels: ["research", "prompt", "investigation", "thai"]
body:
  - type: markdown
    attributes:
      value: |
        ## เทมเพลตคำแนะนำการวิจัย
        ใช้คำแนะนำที่มีโครงสร้างนี้เพื่อเป็นแนวทางการวิจัยการทำเบียร์อย่างครอบคลุม เพื่อให้แน่ใจว่าการสืบสวนมีความสม่ำเสมอและละเอียดถี่ถ้วน

  - type: input
    id: prompt-title
    attributes:
      label: ชื่อคำแนะนำการวิจัย
      description: ชื่อที่ชัดเจนและเฉพาะเจาะจงสำหรับคำแนะนำการวิจัยนี้
      placeholder: "เช่น วิเคราะห์สายพันธุ์ยีสต์ Belgian Wit เพื่อพัฒนาโปรไฟล์รสชาติ"
    validations:
      required: true
  
  - type: input
    id: linked-request
    attributes:
      label: คำขอการวิจัยที่เชื่อมโยง
      description: หมายเลข issue ของคำขอการวิจัยต้นฉบับ
      placeholder: "#123"
    validations:
      required: true
  
  - type: textarea
    id: research-prompt
    attributes:
      label: คำแนะนำการวิจัยที่มีโครงสร้าง
      description: คำแนะนำละเอียดเพื่อเป็นแนวทางการวิจัย
      value: |
        ## บริบทการวิจัย
        [ให้ข้อมูลพื้นฐานและเหตุผลที่การวิจัยนี้มีความสำคัญ]
        
        ## คำถามการวิจัยหลัก
        1. [คำถามเฉพาะ 1]
        2. [คำถามเฉพาะ 2]
        3. [คำถามเฉพาะ 3]
        
        ## วิธีการวิจัย
        ### การทบทวนวรรณกรรม
        - [ ] วารสารการทำเบียร์ทางวิชาการ
        - [ ] สิ่งพิมพ์ในอุตสาหกรรม
        - [ ] ตำราการทำเบียร์ทางประวัติศาสตร์
        - [ ] ข้อมูลจำเพาะทางเทคนิค
        
        ### การวิเคราะห์เชิงปฏิบัติ
        - [ ] ตัวอย่างเบียร์เชิงพาณิชย์
        - [ ] ข้อมูลจำเพาะวัตถุดิบ
        - [ ] พารามิเตอร์กระบวนการ
        - [ ] เมตริกคุณภาพ
        
        ### การเก็บรวบรวมข้อมูล
        - [ ] การวัดเชิงปริมาณที่จำเป็น
        - [ ] การประเมินเชิงคุณภาพที่ต้องการ
        - [ ] กรอบการเปรียบเทียบ
        
        ## ผลลัพธ์ที่คาดหวัง
        1. **เอกสารวิจัยครอบคลุม**
           - หลักการทางวิทยาศาสตร์
           - การประยุกต์ใช้เชิงปฏิบัติ
           - แนวทางปฏิบัติที่ดี
           
        2. **กรอบสูตร**
           - ข้อแนะนำวัตถุดิบ
           - พารามิเตอร์กระบวนการ
           - ข้อมูลจำเพาะเป้าหมาย
           
        3. **ข้อเสนอการทดลอง**
           - สมมติฐานที่จะทดสอบ
           - ตัวแปรที่จะควบคุม
           - เมตริกความสำเร็จ
    validations:
      required: true
  
  - type: checkboxes
    id: research-sources
    attributes:
      label: แหล่งการวิจัยที่จะศึกษา
      description: แหล่งไหนที่ควรสืบสวน?
      options:
        - label: วรรณกรรมการทำเบียร์ทางวิทยาศาสตร์
        - label: เอกสารทางเทคนิคของอุตสาหกรรม
        - label: เอกสารการทำเบียร์ทางประวัติศาสตร์
        - label: การวิเคราะห์ผลิตภัณฑ์เชิงพาณิชย์
        - label: ความรู้ชุมชนผู้ทำเบียร์
        - label: ข้อมูลทางเทคนิคของผู้จำหน่าย
        - label: แนวทางสไตล์การแข่งขัน
        - label: การสัมภาษณ์ผู้ทำเบียร์มืออาชีพ
  
  - type: textarea
    id: output-structure
    attributes:
      label: โครงสร้างผลลัพธ์การวิจัย
      description: ผลการค้นพบควรจัดระเบียบอย่างไร?
      value: |
        ## ที่ตั้งผลลัพธ์: brews/001-research-outputs/[หมวดหมู่]/[หัวข้อ].md
        
        ### โครงสร้างเอกสาร:
        1. **บทสรุปสำหรับผู้บริหาร** (ผลการค้นพบสำคัญใน 3-5 ข้อ)
        2. **พื้นฐานและบริบท**
        3. **หลักการทางวิทยาศาสตร์**
        4. **การประยุกต์ใช้เชิงปฏิบัติ**
        5. **การวิเคราะห์ตัวอย่างเชิงพาณิชย์**
        6. **แนวทางการพัฒนาสูตร**
        7. **โอกาสการทดลอง**
        8. **แนวทางปฏิบัติที่ดีและข้อแนะนำ**
        9. **ปัญหาทั่วไปและวิธีแก้ไข**
        10. **อ้างอิงและการอ่านเพิ่มเติม**
  
  - type: textarea
    id: analysis-framework
    attributes:
      label: กรอบการวิเคราะห์
      description: วิธีการวิเคราะห์และเปรียบเทียบผลการค้นพบ
      placeholder: |
        - เมทริกซ์การเปรียบเทียบสำหรับตัวเลือกที่คล้ายกัน
        - เมตริกเชิงปริมาณและช่วง
        - เกณฑ์การประเมินเชิงคุณภาพ
        - ต้นไม้การตัดสินใจสำหรับการเลือก
  
  - type: checkboxes
    id: deliverable-checklist
    attributes:
      label: รายการตรวจสอบผลลัพธ์การวิจัย
      description: ตรวจสอบให้แน่ใจว่าผลลัพธ์ครอบคลุม
      options:
        - label: เอกสารวิจัยสร้างใน 001-research-outputs/
        - label: แนวคิดสูตรอย่างน้อย 3 แนวคิดใน 002-recipes/experimental/
        - label: ข้อเสนอการทดลอง 2+ ใน 003-experiments/planned/
        - label: รายการฐานความรู้ใน 006-knowledge-base/
        - label: เพิ่มการอ้างอิงไปยังการวิจัยที่เกี่ยวข้อง
        - label: สร้างสื่อช่วยภาพ (แผนภูมิ, ไดอะแกรม, ตาราง)
  
  - type: textarea
    id: recipe-applications
    attributes:
      label: การประยุกต์ใช้การพัฒนาสูตร
      description: การวิจัยนี้จะแปลงเป็นสูตรได้อย่างไร?
      placeholder: |
        - การรวมวัตถุดิบเฉพาะที่จะทดสอบ
        - การปรับเปลี่ยนกระบวนการที่จะดำเนินการ
        - ข้อมูลจำเพาะเป้าหมายที่จะบรรลุ
        - การปรับปรุงคุณภาพที่คาดหวัง